config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :champions, only: [:index, :show]
  resources :animes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/champion.rb
class Champion < ApplicationRecord  
end

app/controllers/animes_controller.rb
class AnimesController < ApplicationController
  def index
  end

  def show
    @anime = JinkanService.anime_details(params[:id])
    if @anime
      render json: @anime
    else
      render json: { error: 'Anime not found' }, status: :not_found
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/champions_controller.rb
class ChampionsController < ApplicationController
  def index
    @champions = DataDragonService.champions
  end

  def show
    @champion = DataDragonService.champion_details(params[:id])
    if @champion
      Rails.logger.debug("Success retrieving champion")
    else
      Rails.logger.debug("Failed retrieving champion")
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/animes_helper.rb
module AnimesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/champions_helper.rb
module ChampionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/animes/index.html.erb
<h1>Animes#index</h1>
<p>Find me in app/views/animes/index.html.erb</p>

app/views/animes/show.html.erb
<h1>Animes#show</h1>
<p>Find me in app/views/animes/show.html.erb</p>

app/views/champions/index.html.erb
<h1>Champions list</h1>

<ul>
    <% @champions.each do |key, champ| %>
        <li>
            <!-- Passing only the ID of a champion when we are dealing with json -->
            <%= link_to "#{champ['name']}", champion_path(champ['id']) %> 
        </li>
    <% end %>
</ul>

app/views/champions/show.html.erb
<h1>Champions#show</h1>

<ul>
    <li><%= @champion['name'] %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ApiEx</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/_navbar.html.erb
<nav id='menu'>
  <input type='checkbox' id='responsive-menu'><label></label>
  <ul>
    <li><%= link_to "Home", root_path %></li>
    <li><a class='dropdown-arrow' href='http://'>Products</a>
      <ul class='sub-menus'>
      </ul>
    </li>
    <li><a href='http://'>About</a></li>
    <li><a class='dropdown-arrow' href='http://'>Services</a>
      <ul class='sub-menus'>
      </ul>
    </li>
    <li><a href='http://'>Contact Us</a></li>
  </ul>
</nav>

app/views/welcome/index.html.erb
<%
=begin%>
 <%= render "navbar" %> 
<%
=end%>

<h1>Simple website consuming Valorant API</h1>

<%= link_to "Champions", champions_path %>